# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAnalysis', '0003_auto_20170523_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='uploadFile',
            new_name='uploaded_to',
        ),
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploadFile',
        ),
        migrations.AddField(
            model_name='image',
            name='imageFile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ImageAnalysis.UploadFile'),
            preserve_default=False,
        ),
    ]
