# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAnalysis', '0004_auto_20170523_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='uploaded_to',
            new_name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='imageFile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ImageAnalysis.UploadFile'),
        ),
    ]
