# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAnalysis', '0005_auto_20170524_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageName',
            field=models.CharField(default='frame-r-006709-3-0028_0xCbLhz.png', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='obsTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 1, 41, 50, 567526, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='previewName',
            field=models.CharField(default='frame-r-006709-3-0028_0xCbLhz.png', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='ImageAnalysis/static/astroImages/'),
        ),
    ]
